package runner

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"changkun.de/wallfacer/internal/envconfig"
	"changkun.de/wallfacer/internal/logger"
	"changkun.de/wallfacer/internal/store"
	"github.com/google/uuid"
)

// GenerateOversight produces a high-level aggregated summary of a task's agent
// execution trace and persists it as oversight.json in the task directory.
//
// For "waiting" transitions it is called synchronously so that the oversight is
// always in a terminal state (ready or failed) by the time the task status
// becomes visible as "waiting". For "done" transitions it is launched as a
// tracked background goroutine via backgroundWg.
//
// The summary is generated by running a lightweight agent container that
// receives a pre-processed compact activity log extracted from the raw NDJSON
// turn output files. The agent groups the activities into logical phases and
// produces a structured JSON response.
//
// Concurrent calls for the same task are serialized via a per-task mutex so
// that periodic and terminal invocations never interleave.
func (r *Runner) GenerateOversight(taskID uuid.UUID) {
	mu := r.oversightLock(taskID)
	mu.Lock()
	defer mu.Unlock()
	r.generateOversightLocked(taskID)
}

// generateOversightLocked is the implementation of GenerateOversight.
// The caller must hold the per-task oversightLock before calling this function.
func (r *Runner) generateOversightLocked(taskID uuid.UUID) {
	ctx := context.Background()

	// Mark as generating so the UI can show a loading state.
	_ = r.store.SaveOversight(taskID, store.TaskOversight{
		Status: store.OversightStatusGenerating,
	})

	log, err := r.buildActivityLog(ctx, taskID, 1)
	if err != nil {
		logger.Runner.Warn("oversight: build activity log", "task", taskID, "error", err)
		_ = r.store.SaveOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  fmt.Sprintf("build activity log: %v", err),
		})
		return
	}

	if len(log) == 0 {
		// No turns yet — nothing to summarize.
		_ = r.store.SaveOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  "no agent activity found",
		})
		return
	}

	phases, err := r.runOversightAgent(taskID, "oversight", log)
	if err != nil {
		logger.Runner.Warn("oversight: agent failed", "task", taskID, "error", err)
		_ = r.store.SaveOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  fmt.Sprintf("oversight agent: %v", err),
		})
		return
	}

	if err := r.store.SaveOversight(taskID, store.TaskOversight{
		Status:      store.OversightStatusReady,
		GeneratedAt: time.Now(),
		Phases:      phases,
	}); err != nil {
		logger.Runner.Warn("oversight: save failed", "task", taskID, "error", err)
	}
}

// GenerateTestOversight produces a high-level aggregated summary of the test
// agent's execution turns and persists it as oversight-test.json in the task
// directory. fromTurn is the implementation's last turn count; only turns
// strictly after this boundary (fromTurn+1 onwards) are included.
//
// It is called synchronously after a test run transitions the task back to
// "waiting", so the summary is always in a terminal state when the task
// becomes visible as "waiting".
//
// Concurrent calls for the same task are serialized via a per-task mutex.
func (r *Runner) GenerateTestOversight(taskID uuid.UUID, fromTurn int) {
	mu := r.oversightLock(taskID)
	mu.Lock()
	defer mu.Unlock()
	r.generateTestOversightLocked(taskID, fromTurn)
}

// generateTestOversightLocked is the implementation of GenerateTestOversight.
// The caller must hold the per-task oversightLock before calling this function.
func (r *Runner) generateTestOversightLocked(taskID uuid.UUID, fromTurn int) {
	ctx := context.Background()

	_ = r.store.SaveTestOversight(taskID, store.TaskOversight{
		Status: store.OversightStatusGenerating,
	})

	log, err := r.buildActivityLog(ctx, taskID, fromTurn+1)
	if err != nil {
		logger.Runner.Warn("test oversight: build activity log", "task", taskID, "error", err)
		_ = r.store.SaveTestOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  fmt.Sprintf("build activity log: %v", err),
		})
		return
	}

	if len(log) == 0 {
		_ = r.store.SaveTestOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  "no test agent activity found",
		})
		return
	}

	phases, err := r.runOversightAgent(taskID, "oversight-test", log)
	if err != nil {
		logger.Runner.Warn("test oversight: agent failed", "task", taskID, "error", err)
		_ = r.store.SaveTestOversight(taskID, store.TaskOversight{
			Status: store.OversightStatusFailed,
			Error:  fmt.Sprintf("oversight agent: %v", err),
		})
		return
	}

	if err := r.store.SaveTestOversight(taskID, store.TaskOversight{
		Status:      store.OversightStatusReady,
		GeneratedAt: time.Now(),
		Phases:      phases,
	}); err != nil {
		logger.Runner.Warn("test oversight: save failed", "task", taskID, "error", err)
	}
}

// oversightIntervalFromEnv reads WALLFACER_OVERSIGHT_INTERVAL from the env file
// and returns it as a time.Duration. Returns 0 if the file is missing, unset,
// or set to 0 (disabled). Mirrors the pattern used by titleModelFromEnv.
func (r *Runner) oversightIntervalFromEnv() time.Duration {
	if r.envFile == "" {
		return 0
	}
	cfg, err := envconfig.Parse(r.envFile)
	if err != nil {
		return 0
	}
	if cfg.OversightInterval <= 0 {
		return 0
	}
	return time.Duration(cfg.OversightInterval) * time.Minute
}

// periodicOversightWorker generates oversight summaries on a fixed interval
// while the task context (Run's execution context) is alive. It skips a tick
// if generation is already in progress (TryLock fails) and re-reads the
// configured interval on each tick so operator changes take effect live.
func (r *Runner) periodicOversightWorker(ctx context.Context, taskID uuid.UUID) {
	interval := r.oversightIntervalFromEnv()
	if interval == 0 {
		return // disabled; exit immediately
	}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			newInterval := r.oversightIntervalFromEnv()
			if newInterval == 0 {
				return // disabled at runtime; stop
			}
			if newInterval != interval {
				interval = newInterval
				ticker.Reset(interval)
			}

			// Skip if a generation is already in progress for this task.
			mu := r.oversightLock(taskID)
			if !mu.TryLock() {
				continue
			}

			// Skip if there is no agent output yet.
			entries, err := os.ReadDir(r.store.OutputsDir(taskID))
			if err == nil && len(entries) > 0 {
				r.generateOversightLocked(taskID)
			}
			mu.Unlock()
		}
	}
}

// turnActivity is a pre-processed per-turn summary used to build the oversight prompt.
type turnActivity struct {
	Turn      int
	Timestamp time.Time
	TextNotes []string // assistant text snippets (≤200 chars each)
	ToolCalls []string // "ToolName(input)" format
}

// buildActivityLog reads all turn NDJSON files and produces a compact per-turn
// activity summary, cross-referencing event timestamps. fromTurn is the first
// turn number to include (1-indexed); pass 1 to include all turns.
func (r *Runner) buildActivityLog(ctx context.Context, taskID uuid.UUID, fromTurn int) ([]turnActivity, error) {
	outputsDir := r.store.OutputsDir(taskID)
	entries, err := os.ReadDir(outputsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	// Build a turn→timestamp index from output events.
	events, _ := r.store.GetEvents(ctx, taskID)
	turnTimestamps := buildTurnTimestamps(events)

	// Collect turn files in order.
	var turnFiles []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		// Only match turn-NNNN.json files (not stderr files).
		if strings.HasPrefix(e.Name(), "turn-") {
			turnFiles = append(turnFiles, filepath.Join(outputsDir, e.Name()))
		}
	}
	sort.Strings(turnFiles)

	var activities []turnActivity
	for i, path := range turnFiles {
		turnNum := i + 1
		if turnNum < fromTurn {
			continue // Skip turns before the requested boundary.
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		act := parseTurnActivity(raw, turnNum)
		if ts, ok := turnTimestamps[turnNum]; ok {
			act.Timestamp = ts
		}
		activities = append(activities, act)
	}
	return activities, nil
}

// buildTurnTimestamps maps turn number → timestamp by scanning span_start
// events for the "agent_turn" phase. Using span_start times (when the
// container began) rather than output event times (when the container
// finished) ensures that phase timestamps align with span.StartedAt in the
// flamegraph, preventing the first span of each phase from being
// misattributed to the preceding phase.
func buildTurnTimestamps(events []store.TaskEvent) map[int]time.Time {
	result := make(map[int]time.Time)
	turn := 0
	for _, e := range events {
		if e.EventType != store.EventTypeSpanStart {
			continue
		}
		var data store.SpanData
		if err := json.Unmarshal(e.Data, &data); err != nil {
			continue
		}
		if data.Phase != "agent_turn" {
			continue
		}
		turn++
		result[turn] = e.CreatedAt
	}
	return result
}

// ndjsonLine is used to parse individual NDJSON messages from agent output.
type ndjsonLine struct {
	Type    string          `json:"type"`
	Message json.RawMessage `json:"message"`
}

type ndjsonMessage struct {
	Content []ndjsonContent `json:"content"`
}

type ndjsonContent struct {
	Type  string          `json:"type"`
	Text  string          `json:"text"`
	Name  string          `json:"name"`
	Input json.RawMessage `json:"input"`
}

// parseTurnActivity extracts tool calls and text snippets from a raw turn NDJSON file.
func parseTurnActivity(raw []byte, turnNum int) turnActivity {
	act := turnActivity{Turn: turnNum}

	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if len(line) == 0 || line[0] != '{' {
			continue
		}
		var msg ndjsonLine
		if err := json.Unmarshal([]byte(line), &msg); err != nil {
			continue
		}
		if msg.Type != "assistant" || len(msg.Message) == 0 {
			continue
		}
		var m ndjsonMessage
		if err := json.Unmarshal(msg.Message, &m); err != nil {
			continue
		}
		for _, block := range m.Content {
			switch block.Type {
			case "text":
				if t := strings.TrimSpace(block.Text); t != "" {
					if len(t) > 200 {
						t = t[:200] + "…"
					}
					act.TextNotes = append(act.TextNotes, t)
				}
			case "tool_use":
				input := extractToolInputGo(block.Name, parseRawInput(block.Input))
				if len(input) > 120 {
					input = input[:120] + "…"
				}
				entry := block.Name
				if input != "" {
					entry += "(" + input + ")"
				}
				act.ToolCalls = append(act.ToolCalls, entry)
			}
		}
	}
	return act
}

// extractToolInputGo returns a short representative string for a tool call
// given the tool name and its input map. Mirrors the logic in modal.js.
func extractToolInputGo(name string, input map[string]interface{}) string {
	if input == nil {
		return ""
	}
	str := func(key string) string {
		if v, ok := input[key]; ok {
			if s, ok := v.(string); ok {
				return s
			}
		}
		return ""
	}
	switch name {
	case "Bash":
		return str("command")
	case "Read":
		return str("file_path")
	case "Write":
		return str("file_path")
	case "Edit":
		return str("file_path")
	case "Glob":
		return str("pattern")
	case "Grep":
		return str("pattern")
	case "WebFetch":
		return str("url")
	case "WebSearch":
		return str("query")
	case "Task":
		if p := str("prompt"); p != "" {
			if len(p) > 120 {
				return p[:120]
			}
			return p
		}
		return ""
	default:
		for _, key := range []string{"file_path", "command", "pattern", "query", "path"} {
			if v := str(key); v != "" {
				return v
			}
		}
		return ""
	}
}

// parseRawInput decodes a JSON raw input into a map for extractToolInputGo.
func parseRawInput(raw json.RawMessage) map[string]interface{} {
	if len(raw) == 0 {
		return nil
	}
	// Try string first (some formats encode input as a JSON string).
	var s string
	if json.Unmarshal(raw, &s) == nil {
		var m map[string]interface{}
		json.Unmarshal([]byte(s), &m)
		return m
	}
	var m map[string]interface{}
	json.Unmarshal(raw, &m)
	return m
}

const oversightPrompt = `You are analyzing the execution trace of an AI coding agent. Your job is to produce a high-level structured summary that helps a human quickly understand what the agent did.

Given the following pre-processed activity log (one section per agent turn):

%s

Produce a JSON response (raw JSON only — no markdown, no code fences, no explanation) with this exact structure:
{
  "phases": [
    {
      "timestamp": "<ISO-8601 datetime of when this phase started, or empty string if unknown>",
      "title": "<Short title, 4-7 words max>",
      "summary": "<1-2 sentence description of what the agent accomplished in this phase>",
      "tools_used": ["<unique tool names used>"],
      "commands": ["<verbatim Bash commands from TOOL: Bash(...) entries in this phase; omit field if none>"],
      "actions": ["<3-7 specific notable actions: what was read, written, searched, run, etc.>"]
    }
  ]
}

Rules:
- Group related turns into logical phases (typically 2-6 phases total)
- Each phase should represent a coherent step (e.g. exploration, planning, implementation, testing, cleanup)
- Use the timestamp of the first turn in each phase
- Keep titles short and action-oriented (e.g. "Explored codebase structure", "Implemented auth handler")
- Keep summaries informative but concise
- List specific filenames or commands in actions where relevant
- In commands, copy each Bash command verbatim from the TOOL: Bash(...) entries (the text inside the parentheses). Include all of them, do not summarize or deduplicate.
- Omit the commands field entirely (or use an empty array) if no Bash tool calls appear in the phase
- Omit phases with no meaningful activity`

// formatActivityLog renders the pre-processed activities as a human-readable text block for the prompt.
func formatActivityLog(activities []turnActivity) string {
	var sb strings.Builder
	for _, a := range activities {
		ts := ""
		if !a.Timestamp.IsZero() {
			ts = a.Timestamp.Format("2006-01-02 15:04:05")
		}
		fmt.Fprintf(&sb, "[Turn %d%s]\n", a.Turn, ifStr(ts != "", " – "+ts, ""))
		for _, note := range a.TextNotes {
			// Indent and prefix with dash; only include if meaningful.
			note = strings.ReplaceAll(strings.TrimSpace(note), "\n", " ")
			fmt.Fprintf(&sb, "  TEXT: %s\n", note)
		}
		for _, call := range a.ToolCalls {
			fmt.Fprintf(&sb, "  TOOL: %s\n", call)
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

func ifStr(cond bool, a, b string) string {
	if cond {
		return a
	}
	return b
}

// oversightPhaseRaw is the JSON shape for a single phase as the agent produces it.
type oversightPhaseRaw struct {
	Timestamp string   `json:"timestamp"`
	Title     string   `json:"title"`
	Summary   string   `json:"summary"`
	ToolsUsed []string `json:"tools_used"`
	Commands  []string `json:"commands"`
	Actions   []string `json:"actions"`
}

// oversightResult is the JSON structure the agent produces.
type oversightResult struct {
	Phases []oversightPhaseRaw `json:"phases"`
}

// runOversightAgent runs a lightweight agent container with the activity log and
// parses the structured JSON it produces. agent is the sub-agent name used for
// usage attribution (e.g. "oversight" or "oversight-test").
func (r *Runner) runOversightAgent(taskID uuid.UUID, agent string, activities []turnActivity) ([]store.OversightPhase, error) {
	log := formatActivityLog(activities)

	// Cap total log size to avoid exceeding prompt limits.
	const maxLogBytes = 40000
	if len(log) > maxLogBytes {
		log = log[:maxLogBytes] + "\n[...truncated...]"
	}

	prompt := fmt.Sprintf(oversightPrompt, log)

	runCtx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	containerName := "wallfacer-oversight-" + taskID.String()[:8]
	exec.Command(r.command, "rm", "-f", containerName).Run()

	task, err := r.store.GetTask(context.Background(), taskID)
	if err != nil {
		logger.Runner.Warn("oversight: get task", "task", taskID, "error", err)
	}
	sandbox := "claude"
	model := ""
	if task != nil {
		sandbox = r.sandboxForTaskActivity(task, activityOversight)
	}
	model = r.titleModelFromEnvForSandbox(sandbox)

	spec := ContainerSpec{
		Runtime: r.command,
		Name:    containerName,
		Image:   r.sandboxImage,
	}
	if r.envFile != "" {
		spec.EnvFile = r.envFile
	}
	if model != "" {
		spec.Env = map[string]string{"CLAUDE_CODE_MODEL": model}
	}
	spec.Volumes = append(spec.Volumes, VolumeMount{
		Host:      "claude-config",
		Container: "/home/claude/.claude",
	})
	spec.Volumes = r.appendCodexAuthMount(spec.Volumes, sandbox)
	// Note: oversight agent uses no workspace mounts, no instructions mount,
	// no -w workdir, and the Cmd order is --output-format before --verbose.
	spec.Cmd = []string{"-p", prompt, "--output-format", "stream-json", "--verbose"}
	if model != "" {
		spec.Cmd = append(spec.Cmd, "--model", model)
	}

	args := spec.Build()
	cmd := exec.CommandContext(runCtx, r.command, args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil && runCtx.Err() == nil {
		return nil, fmt.Errorf("container: %w (stderr: %s)", err, truncate(stderr.String(), 300))
	}

	raw := strings.TrimSpace(stdout.String())
	if raw == "" {
		return nil, fmt.Errorf("empty output from oversight agent")
	}

	output, err := parseOutput(raw)
	if err != nil {
		return nil, fmt.Errorf("parse output: %w", err)
	}

	// Accumulate token/cost usage for this oversight sub-agent.
	if output.Usage.InputTokens > 0 || output.Usage.OutputTokens > 0 || output.TotalCostUSD > 0 {
		if accErr := r.store.AccumulateSubAgentUsage(context.Background(), taskID, agent, store.TaskUsage{
			InputTokens:          output.Usage.InputTokens,
			OutputTokens:         output.Usage.OutputTokens,
			CacheReadInputTokens: output.Usage.CacheReadInputTokens,
			CacheCreationTokens:  output.Usage.CacheCreationInputTokens,
			CostUSD:              output.TotalCostUSD,
		}); accErr != nil {
			logger.Runner.Warn("oversight: accumulate usage failed", "task", taskID, "agent", agent, "error", accErr)
		}
		if appErr := r.store.AppendTurnUsage(taskID, store.TurnUsageRecord{
			Turn:                 1,
			Timestamp:            time.Now().UTC(),
			InputTokens:          output.Usage.InputTokens,
			OutputTokens:         output.Usage.OutputTokens,
			CacheReadInputTokens: output.Usage.CacheReadInputTokens,
			CacheCreationTokens:  output.Usage.CacheCreationInputTokens,
			CostUSD:              output.TotalCostUSD,
			Sandbox:              sandbox,
			SubAgent:             agent,
		}); appErr != nil {
			logger.Runner.Warn("oversight: append turn usage failed", "task", taskID, "agent", agent, "error", appErr)
		}
	}

	phases, err := parseOversightResult(output.Result)
	if err != nil {
		return nil, fmt.Errorf("parse oversight JSON: %w (raw: %s)", err, truncate(output.Result, 400))
	}
	phases = fillMissingPhaseTimestamps(phases, activities)
	return phases, nil
}

// fillMissingPhaseTimestamps assigns proportional timestamps to oversight
// phases when all of them have zero (missing) timestamps. This happens when
// the LLM returns empty strings for the timestamp field.  Phases are
// distributed evenly across the available turn timestamps: phase i is anchored
// to the first turn in its proportional slice of the activity log.
//
// If any phase already carries a non-zero timestamp the slice is returned
// unchanged so that valid partial data is never discarded.
func fillMissingPhaseTimestamps(phases []store.OversightPhase, activities []turnActivity) []store.OversightPhase {
	if len(phases) == 0 || len(activities) == 0 {
		return phases
	}
	// Only intervene when every timestamp is zero.
	for _, p := range phases {
		if !p.Timestamp.IsZero() {
			return phases
		}
	}
	numPhases := len(phases)
	numTurns := len(activities)
	for i := range phases {
		turnIdx := i * numTurns / numPhases
		if turnIdx < numTurns && !activities[turnIdx].Timestamp.IsZero() {
			phases[i].Timestamp = activities[turnIdx].Timestamp
		}
	}
	return phases
}

// parseOversightResult extracts structured phases from Claude's text response.
// Claude is asked to produce raw JSON but may occasionally wrap it in markdown;
// we strip fences and try multiple JSON extraction strategies.
func parseOversightResult(result string) ([]store.OversightPhase, error) {
	// Strip markdown code fences if present.
	result = strings.TrimSpace(result)
	if idx := strings.Index(result, "```"); idx != -1 {
		// Find the content between the first ``` and last ```.
		start := strings.Index(result, "\n")
		end := strings.LastIndex(result, "```")
		if start != -1 && end > start {
			result = strings.TrimSpace(result[start+1 : end])
		}
	}

	// Detect the JSON shape and parse accordingly.
	var rawPhases []oversightPhaseRaw
	switch {
	case strings.HasPrefix(result, "["):
		// Bare array of phase objects: [{...}, {...}]
		if err := json.Unmarshal([]byte(result), &rawPhases); err != nil {
			return nil, err
		}
	case strings.HasPrefix(result, "{"):
		// Object with a "phases" key: {"phases": [{...}]}
		var r oversightResult
		if err := json.Unmarshal([]byte(result), &r); err != nil {
			return nil, err
		}
		rawPhases = r.Phases
	default:
		// Fall back: skip preamble text before the first '{'.
		i := strings.Index(result, "{")
		if i < 0 {
			return nil, fmt.Errorf("no JSON object found in oversight result")
		}
		result = result[i:]
		var r oversightResult
		if err := json.Unmarshal([]byte(result), &r); err != nil {
			return nil, err
		}
		rawPhases = r.Phases
	}

	phases := make([]store.OversightPhase, 0, len(rawPhases))
	for _, p := range rawPhases {
		phase := store.OversightPhase{
			Title:     strings.TrimSpace(p.Title),
			Summary:   strings.TrimSpace(p.Summary),
			ToolsUsed: p.ToolsUsed,
			Commands:  p.Commands,
			Actions:   p.Actions,
		}
		if p.Timestamp != "" {
			// Try several common formats Claude might emit.
			for _, layout := range []string{time.RFC3339, "2006-01-02 15:04:05", "2006-01-02T15:04:05"} {
				if t, err := time.Parse(layout, p.Timestamp); err == nil {
					phase.Timestamp = t
					break
				}
			}
		}
		phases = append(phases, phase)
	}
	return phases, nil
}
